52 style moviemodal
EmpyreanMist/Kino---Cinema pull request #101
Opened 2024-12-24 21:20 UTC by marcusmoller97

* Added style to movie modal to look like in the card.
* Remove exitButton div from modal.
* Made a git pull for  extra functionality from issue #61

2024-12-26 18:20 UTC, NordicNomadicLife approved these changes
looks good

2024-12-26 18:36 UTC, itsJoel59 approved these changes
Nice work, looking forward to seeing the result!

2024-12-26 18:36 UTC, itsJoel59 commented on __tests__/moviesJestTest.spec.js
> +
Nice tests!

2024-12-27 10:07 UTC, kai-ericson requested changes
Nice work! And good job with the tests. There is a merge conflict that needs to be fixed and then it's ready to merge.

2024-12-28 14:35 UTC, kai-ericson approved these changes

2024-12-28 14:35 UTC, merged