47 button
EmpyreanMist/Kino---Cinema pull request #108
Opened 2024-12-28 12:44 UTC by NordicNomadicLife

added a button to go to all movies page just need to add the correct link when the page is created

2024-12-28 22:44 UTC, EmpyreanMist requested changes
Button looks good. Main is now updated with all movies page. Just update the conflicts and link it and we are good to go :)

2024-12-30 09:44 UTC, NordicNomadicLife commented
i have now added the correct link and fixed the conflict

2024-12-30 14:38 UTC, EmpyreanMist commented
There seems to be two navbars
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/9268971b-f25b-4eab-8dad-761c3a17b6e3" />

2025-01-10 10:08 UTC, EmpyreanMist approved these changes

2025-01-10 10:11 UTC, kikoDevv approved these changes
Nicely done!

2025-01-10 10:12 UTC, merged

2025-01-10 10:12 UTC, kikoDevv commented
Its now merged to main